// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3TFJ6q0o4S6czx8heyIutplOlq8EOWFw',
    appId: '1:841481627907:web:55d03683e321892cbc2136',
    messagingSenderId: '841481627907',
    projectId: 'eduflow-student-app-19a5b',
    authDomain: 'eduflow-student-app-19a5b.firebaseapp.com',
    storageBucket: 'eduflow-student-app-19a5b.firebasestorage.app',
    measurementId: 'G-Q926S1KYT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS9u8pSg0vuzl0ZVgwK6sqOKEMAUH2xSw',
    appId: '1:841481627907:android:c5f210ed63a09033bc2136',
    messagingSenderId: '841481627907',
    projectId: 'eduflow-student-app-19a5b',
    storageBucket: 'eduflow-student-app-19a5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlaQDKl66cJqIF_UpKbanaGpOImWQLRMA',
    appId: '1:841481627907:ios:4b0a487dc605d0d0bc2136',
    messagingSenderId: '841481627907',
    projectId: 'eduflow-student-app-19a5b',
    storageBucket: 'eduflow-student-app-19a5b.firebasestorage.app',
    iosBundleId: 'com.example.eduflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlaQDKl66cJqIF_UpKbanaGpOImWQLRMA',
    appId: '1:841481627907:ios:4b0a487dc605d0d0bc2136',
    messagingSenderId: '841481627907',
    projectId: 'eduflow-student-app-19a5b',
    storageBucket: 'eduflow-student-app-19a5b.firebasestorage.app',
    iosBundleId: 'com.example.eduflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3TFJ6q0o4S6czx8heyIutplOlq8EOWFw',
    appId: '1:841481627907:web:e49ae7bc1a03d373bc2136',
    messagingSenderId: '841481627907',
    projectId: 'eduflow-student-app-19a5b',
    authDomain: 'eduflow-student-app-19a5b.firebaseapp.com',
    storageBucket: 'eduflow-student-app-19a5b.firebasestorage.app',
    measurementId: 'G-RZ9WJMWZNH',
  );
}
